[project]
name = "example_package_CNECCC-CSY"
version = "1.0.0"
authors = [
  { name="CNECCC-CSY", email="s2023022@gm.cneccc.edu.hk" },
]
description = "Huh uh"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "WTFPL"

[project.urls]
Homepage = "https://github.com/CNECCC-CSY/Nuh-uh/"
Issues = "https://github.com/CNECCC-CSY/Nuh-uh/issues"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
