[project]
name = "example_package_27e31d54-9c0c-4eca-a28a-2766b97fe294"
version = "1.0.0"
authors = [
  { name="CNECCC-CSY", email="s2023022@gm.cneccc.edu.hk" },
]
description = "Huh uh"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"


[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
